services:
  - type: web
    name: webrtc-signaling-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
    healthCheckPath: /health
