<?php
/**
 * ONE-CLICK INSTALLER
 * Run this file once on your PHP host to set up the full database and config.
 * Delete or rename after install for security.
 */

$step = $_POST['step'] ?? 'form';
$error = '';
$success = '';

if ($step === 'install' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $host   = trim($_POST['db_host']);
    $dbname = trim($_POST['db_name']);
    $user   = trim($_POST['db_user']);
    $pass   = trim($_POST['db_pass']);
    $admin_user = trim($_POST['admin_user']);
    $admin_pass = trim($_POST['admin_pass']);
    $node_url   = rtrim(trim($_POST['node_url']), '/');

    try {
        $pdo = new PDO("mysql:host=$host;charset=utf8mb4", $user, $pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
        ]);

        // Create database
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `$dbname` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $pdo->exec("USE `$dbname`");

        // Admin users table
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS `admins` (
                `id` INT AUTO_INCREMENT PRIMARY KEY,
                `username` VARCHAR(100) NOT NULL UNIQUE,
                `password` VARCHAR(255) NOT NULL,
                `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
            ) ENGINE=InnoDB
        ");

        // Devices table
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS `devices` (
                `id` INT AUTO_INCREMENT PRIMARY KEY,
                `device_id` VARCHAR(100) NOT NULL UNIQUE,
                `device_name` VARCHAR(200),
                `last_seen` DATETIME,
                `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
            ) ENGINE=InnoDB
        ");

        // Media captures table (temporary storage)
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS `media_captures` (
                `id` INT AUTO_INCREMENT PRIMARY KEY,
                `device_id` VARCHAR(100) NOT NULL,
                `media_type` ENUM('image','audio','video') NOT NULL,
                `filename` VARCHAR(300) NOT NULL,
                `file_path` VARCHAR(500) NOT NULL,
                `file_size` INT DEFAULT 0,
                `captured_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                `expires_at` DATETIME DEFAULT NULL,
                INDEX (`device_id`),
                INDEX (`media_type`),
                INDEX (`captured_at`)
            ) ENGINE=InnoDB
        ");

        // Insert admin user
        $hashed = password_hash($admin_pass, PASSWORD_BCRYPT);
        $stmt = $pdo->prepare("INSERT IGNORE INTO `admins` (username, password) VALUES (?, ?)");
        $stmt->execute([$admin_user, $hashed]);

        // Write config file
        $config_content = "<?php\n// Auto-generated by install.php\ndefine('DB_HOST', '$host');\ndefine('DB_NAME', '$dbname');\ndefine('DB_USER', '$user');\ndefine('DB_PASS', '$pass');\ndefine('NODE_BACKEND_URL', '$node_url');\ndefine('MEDIA_UPLOAD_DIR', __DIR__ . '/uploads/');\ndefine('MEDIA_TEMP_EXPIRY_HOURS', 24); // Auto-delete after 24 hours\nsession_start();\n";
        file_put_contents(__DIR__ . '/config.php', $config_content);

        // Create uploads dir
        if (!is_dir(__DIR__ . '/uploads')) {
            mkdir(__DIR__ . '/uploads', 0755, true);
            file_put_contents(__DIR__ . '/uploads/.htaccess', 'Options -Indexes\n');
        }

        $success = 'Installation complete! <a href="index.php">Go to Dashboard</a>. Delete install.php for security.';
    } catch (Exception $e) {
        $error = 'Error: ' . $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Install - ParentControl Dashboard</title>
<style>
body{font-family:Arial,sans-serif;background:#1a1a2e;color:#eee;display:flex;justify-content:center;align-items:center;min-height:100vh;margin:0}
.box{background:#16213e;padding:2rem;border-radius:12px;width:400px;box-shadow:0 4px 20px rgba(0,0,0,.5)}
h2{color:#e94560;margin-top:0}input{width:100%;padding:10px;margin:6px 0 14px;background:#0f3460;border:1px solid #444;border-radius:6px;color:#fff;box-sizing:border-box}
btn, button{width:100%;padding:12px;background:#e94560;border:none;border-radius:6px;color:#fff;font-size:16px;cursor:pointer}
.err{color:#ff6b6b;margin-bottom:10px}.suc{color:#6bff9e;margin-bottom:10px}
</style>
</head>
<body>
<div class="box">
  <h2>⚙️ One-Click Installer</h2>
  <?php if ($error): ?><div class="err"><?= htmlspecialchars($error) ?></div><?php endif; ?>
  <?php if ($success): ?><div class="suc"><?= $success ?></div><?php else: ?>
  <form method="POST">
    <input type="hidden" name="step" value="install">
    <label>DB Host</label><input name="db_host" value="localhost" required>
    <label>DB Name</label><input name="db_name" value="parentcontrol" required>
    <label>DB User</label><input name="db_user" required>
    <label>DB Password</label><input type="password" name="db_pass">
    <label>Admin Username</label><input name="admin_user" value="admin" required>
    <label>Admin Password</label><input type="password" name="admin_pass" required>
    <label>Node.js Backend URL (Render)</label><input name="node_url" placeholder="https://your-app.onrender.com" required>
    <button type="submit">Install Now</button>
  </form>
  <?php endif; ?>
</div>
</body>
</html>
